package com.kita.first.level4;

import java.util.Scanner;

public class ThrowsException {
	
	Scanner scan = new Scanner(System.in);
	
	void method1() throws Exception{
		int num = Integer.parseInt(scan.next());

		
		
		
		
//		try {
//			
//		}catch(NullPointerException e){  //참조변수 안에 연결된 값이 없을 경우
//			
//		}catch(Exception e){  //익셉션e는 마지막에
//			
//		}finally {
//			
//		}
	}
}
